### ISSUE TITLE
[Discussions] ios存在点击穿透问题，点击全屏下的授权页面会导致flutter页面被点击 以及其它问题

### ISSUE THREAD

**Issue by shenhuaxiyuan** [ManInTheWind/flutter_ali_auth#10]
### Content

在flutter登录页面调用一键登录，然后在全屏模式下的授权页空白处点击，或者点击有按钮的地方，都会触发flutter页面的点击，导致flutter页面被误点。
另外安卓CheckBoxConfig中的checkedImage需要手动补上flutter_assets/前缀，图片才能出来。
再就是安卓手机的关闭按钮太靠下了点，但是offsetY已经是0了。

Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale zh-Hans-CN)

**Comment by shenhuaxiyuan** [comment]
点击穿透仅ios存在问题，安卓没问题

**Comment by lurongshuang** [comment]
问题解决了吗？
