### ISSUE TITLE
[Discussions] Android在全屏号码认证页面关闭网络后会由于loading卡死

### ISSUE THREAD

**Issue by shenhuaxiyuan** [ManInTheWind/flutter_ali_auth#11]
### Content

我看log里面是有一个102101状态码的，但是这个状态码并没有被返回到flutter端，导致无法手动关闭loading。
不着到为什么我选择提交bug选项，但是必填项里面Platform里面无法选中任何项，所以无法提交，就改成了Discussions。

**Comment by ManInTheWind** [comment]
穿透问题请找Flutter官方。其余问题请更新到[v0.6.2](https://pub.flutter-io.cn/packages/flutter_ali_auth/versions/0.6.2)
