### ISSUE TITLE
PrivacyConfig中privacyUrl填写本地和网络地址均无效

### ISSUE THREAD

**Issue by Cryptorcheck** [ManInTheWind/flutter_ali_auth#15]
### Version

0.6.2

### Platforms

iOS

### Device Model

ip12

### flutter info

```sh
privacyConfig: PrivacyConfig(
        privacyFontColor: '#EB2500',
        privacyOneName: '《隐私协议》',
        privacyOneUrl: 'assets/html/privacy-agreement.html',
      ),
```

### How to reproduce?

privacyConfig: PrivacyConfig(
        privacyFontColor: '#EB2500',
        privacyOneName: '《隐私协议》',
        privacyOneUrl: 'assets/html/privacy-agreement.html',
      ),

### Contact

243979384@qq.com

**Comment by ManInTheWind** [comment]
你填个本地的做什么？
