### ISSUE TITLE
Flutter方法回调问题

### ISSUE THREAD

**Issue by lionnner** [ManInTheWind/flutter_ali_auth#2]
AliAuthClient 这个类的回调参数其实都是通过EventChannel获取到的，
1. 那么 static Future<AuthResponseModel> initSdk() static Future<AuthResponseModel> login() 这些方法 其实写成 static void initSdk() static void login() 更好一些吧。
2. EventChannel回调给flutter的时候，是不是带上方法的名字更好一些("init"/ "checkEnv")，这样方便知道是哪个方法响应的。
3. 通过MethodChannel回调给flutter端可能更符合使用的场景。

**Comment by ManInTheWind** [comment]
1.之前这几个初始化接口是设计成void，但是后面发现ios和android这两sdk的回调不尽相同，现在设置有response可以暂时忽略
2.建议按照demo的主要几个responseCode进行判断就行，初始化成功/失败，环境可用/不可用
3.统一用Eventchannel是因为安卓的checkEnv不是马上回调的，是在初始化的时候设置监听器监听，还有调起授权页面的事件只能监听
4.目前一些接口还没完全完善，欢迎pr

**Comment by ManInTheWind** [comment]
1.之前这几个初始化接口是设计成void，但是后面发现ios和android这两sdk的回调不尽相同，现在设置有response可以暂时忽略
2.建议按照demo的主要几个responseCode进行判断就行，初始化成功/失败，环境可用/不可用
3.统一用Eventchannel是因为安卓的checkEnv不是马上回调的，是在初始化的时候设置监听器监听，还有调起授权页面的事件只能监听
4.目前一些接口还没完全完善，欢迎pr
