### ISSUE TITLE
ios 16.4开始的系统版本用不了一键登陆了

### ISSUE THREAD

**Issue by 153104373** [ManInTheWind/flutter_ali_auth#25]
### Platforms

iOS

### Description

反馈 下flutter_ali_auth的这个插件，报600004。ios 16.4的版本用不了一键登录了。需要更新Ios的系统库版本了。也不知道ios为啥系统版本一更新，很多原生库都用不了

### Why

ios 16.4开始的系统版本用不了一键登陆了

**Comment by cocoa78** [comment]
官网说 从iOS16.4开始，iOS系统开始废弃CTCarrier功能，并不再提供替代方案, 需要将号码认证SDK版本更新到 v2.12.14或以上版本, https://help.aliyun.com/document_detail/2326795.html?spm=a2c4g.615160.0.0.609a4eda2p8DMo

**Comment by 153104373** [comment]
> 官网说 从iOS16.4开始，iOS系统开始废弃CTCarrier功能，并不再提供替代方案, 需要将号码认证SDK版本更新到 v2.12.14或以上版本, https://help.aliyun.com/document_detail/2326795.html?spm=a2c4g.615160.0.0.609a4eda2p8DMo

但是flutter_ali_auth的插件的sdk还没有更新

**Comment by 153104373** [comment]
> 官网说 从iOS16.4开始，iOS系统开始废弃CTCarrier功能，并不再提供替代方案, 需要将号码认证SDK版本更新到 v2.12.14或以上版本, https://help.aliyun.com/document_detail/2326795.html?spm=a2c4g.615160.0.0.609a4eda2p8DMo

预计下一个flutter_ali_auth的ios 的SDK版本，什么时候更新啊

**Comment by lurongshuang** [comment]
自己手动更新吧 插件下载到本地，替换SDK文件 #23

**Comment by 153104373** [comment]
是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？

**Comment by 153104373** [comment]
> 是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？


> 自己手动更新吧 插件下载到本地，替换SDK文件 #23


请问是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？主要是重来没有接触过IOS

**Comment by lurongshuang** [comment]
> > 是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？
> 
> > 自己手动更新吧 插件下载到本地，替换SDK文件 #23
> 
> 请问是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？主要是重来没有接触过IOS

我目前是这样做的，是可以的

**Comment by 153104373** [comment]
> > > 是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？
> > 
> > 
> > > 自己手动更新吧 插件下载到本地，替换SDK文件 #23
> > 
> > 
> > 请问是直接把下载的SDK。直接替换下 ios/frameworks的文件就可以了吗？主要是重来没有接触过IOS
> 
> 我目前是这样做的，是可以的

感觉，我试了，确实是可以用

**Comment by ManInTheWind** [comment]
[v0.7.0](https://github.com/fluttercandies/flutter_ali_auth/tree/v0.7.0)已支持
