### ISSUE TITLE
安卓环境下sloganConfig 设置不生效

### ISSUE THREAD

**Issue by ZhangZhiH** [ManInTheWind/flutter_ali_auth#4]
flutter 3.3.0
安卓 12
小米10 
设置了  sloganConfig: const SloganConfig(sloganText: '使用本机号码一键登录'), 无法生效
```
 final AuthConfig _authConfig = AuthConfig(
    enableLog: false,
    authUIStyle: AuthUIStyle.fullScreen,
    authUIConfig: FullScreenUIConfig(
      navConfig: NavConfig(navColor: Colors.pinkAccent.toHex()),
      logoConfig: const LogoConfig(logoImage: "images/app_icon"),
      sloganConfig: const SloganConfig(sloganText: '使用本机号码一键登录'),
    ),
  );
```
![20e3e133741941cde412353a18d695d](https://user-images.githubusercontent.com/14193471/211472528-9025b711-b63c-4faf-b778-1d0e1a8f3d00.jpg)

**Comment by ManInTheWind** [comment]
等下我看看

**Comment by ManInTheWind** [comment]
弹窗模式下的slogan都是默认不显示的，sloganIsHidden设为false就行

**Comment by ZhangZhiH** [comment]
感谢楼主 已经解决问题 0.1 不可以 0.2 可以了

**Comment by ManInTheWind** [comment]
0.1和0.2都是一样的，如果有问题，就先不要用copyWith。0.2我已经取消掉了
