### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by cw0925** [ManInTheWind/flutter_ali_auth#9]
### Platforms

Android, iOS

### Description

![p480101](https://user-images.githubusercontent.com/17431906/227903952-c2e15a35-99de-4de7-8c73-d3b1d7627180.png)
你好，想问下这个二次授权弹窗页面有实现吗，或者有什么方法在授权页面显示一个弹窗，现在授权页面的层级太高，把弹窗都遮盖了。

**Comment by ManInTheWind** [comment]
没实现。后面看需求的人多了再支持
